# Generated by Django 3.0.3 on 2020-03-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thank_logan', '0002_auto_20200229_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thank', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='thank_logan.Thank')),
            ],
        ),
    ]
