# Generated by Django 3.0.3 on 2020-03-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thank_logan', '0003_smsqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='thank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thank_logan.Thank'),
        ),
    ]
